---
networks:
  local-network:
    name: app-abc
services:
  jaeger:
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    hostname: jaeger
    image: jaegertracing/all-in-one:latest
    networks:
      - local-network
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "9411:9411"
    restart: always
  app-a:
    container_name: app-a
    depends_on:
      - jaeger
    environment:
      - CONF_FILE=/etc/app-abc/config.yaml
    hostname: app-a
    image: boeboe/demo-app-abc
    networks:
      - local-network
    ports:
      - "5000:5000"
    restart: always
    volumes:
        - ${PWD}/config/config-app-a.yaml:/etc/app-abc/config.yaml
  app-b:
    container_name: app-b
    depends_on:
      - jaeger
      - app-a
    environment:
      - CONF_FILE=/etc/app-abc/config.yaml
    hostname: app-b
    image: boeboe/demo-app-abc
    networks:
      - local-network
    ports:
      - "5001:5001"
    restart: always
    volumes:
        - ${PWD}/config/config-app-b.yaml:/etc/app-abc/config.yaml
  app-c:
    container_name: app-c
    depends_on:
      - jaeger
      - app-b
    environment:
      - CONF_FILE=/etc/app-abc/config.yaml
    hostname: app-c
    image: boeboe/demo-app-abc
    networks:
      - local-network
    ports:
      - "5002:5002"
    restart: always
    volumes:
        - ${PWD}/config/config-app-c.yaml:/etc/app-abc/config.yaml
